server:
  port: ${APPLICATION_PORT}

spring:
  profiles:
    active: dev
  application:
    name: PncaMusic
  datasource:
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?characterEncoding=UTF8&userSSL=false
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

